version: '3.6'

services:
  vault:
    image: vault:1.13.3
    healthcheck:
      retries: 5
    restart: always
    ports:
      - 8200:8200
    networks:
      - kind
      - infra
    environment:
      VAULT_ADDR: 'https://0.0.0.0:8200'
      VAULT_LOCAL_CONFIG: '{"listener": [{"tcp":{"address": "0.0.0.0:8200","tls_disable":"1"}}], "ui": true, "storage": [{"file": {"path":"/vault/data"}}]}'
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault/config:/vault/config
      - ./vault/data:/vault/data
    command: vault server -config vault/config/local.json
networks:
  kind: # define the kind network
    external: true # specifies that the network already exists in docker
  infra:
    external: true