apiVersion: v2
name: argo-cd
version: 1.0.0
dependencies:
- name: argo-cd
  version: 7.3.9
  repository: https://argoproj.github.io/argo-helm
- name: ingress-nginx
  version: 4.11.0
  repository: https://kubernetes.github.io/ingress-nginx
